//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessManager.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    
    public partial class Choir : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	protected virtual void OnPropertyChanged(string propertyName)
    	{
            if (PropertyChanged!= null) 
    		{
    			PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    		}
    	}
    
        public Choir()
        {
            this.Students = new HashSet<Student>();
            this.Rolls = new HashSet<Roll>();
        }
    
    	private System.Guid id;
    
        public System.Guid Id 
    	{ 
    		get { return id; } 
    		set
    		{
    			id = value;
    			//OnPropertyChanged("Id");
    		} 
    	}
    
    	private string name;
    
        public string Name 
    	{ 
    		get { return name; } 
    		set
    		{
    			name = value;
    			//OnPropertyChanged("Name");
    		} 
    	}
    
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Roll> Rolls { get; set; }
    }
}
