//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessManager.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    
    public partial class Payment : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	protected virtual void OnPropertyChanged(string propertyName)
    	{
            if (PropertyChanged!= null) 
    		{
    			PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    		}
    	}
    
    	private System.Guid id;
    
        public System.Guid Id 
    	{ 
    		get { return id; } 
    		set
    		{
    			id = value;
    			//OnPropertyChanged("Id");
    		} 
    	}
    
    	private Nullable<System.Guid> studentid;
    
        public Nullable<System.Guid> StudentId 
    	{ 
    		get { return studentid; } 
    		set
    		{
    			studentid = value;
    			//OnPropertyChanged("StudentId");
    		} 
    	}
    
    	private Nullable<decimal> amount;
    
        public Nullable<decimal> Amount 
    	{ 
    		get { return amount; } 
    		set
    		{
    			amount = value;
    			//OnPropertyChanged("Amount");
    		} 
    	}
    
    
        public virtual Student Student { get; set; }
    }
}
