//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessManager.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    
    public partial class SheetMusic : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	protected virtual void OnPropertyChanged(string propertyName)
    	{
            if (PropertyChanged!= null) 
    		{
    			PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    		}
    	}
    
        public SheetMusic()
        {
            this.Artists = new HashSet<Artist>();
            this.Composers = new HashSet<Artist>();
        }
    
    	private System.Guid id;
    
        public System.Guid Id 
    	{ 
    		get { return id; } 
    		set
    		{
    			id = value;
    			OnPropertyChanged("Id");
    		} 
    	}
    
    	private string title;
    
        public string Title 
    	{ 
    		get { return title; } 
    		set
    		{
    			title = value;
    			OnPropertyChanged("Title");
    		} 
    	}
    
    	private bool isoriginal;
    
        public bool IsOriginal 
    	{ 
    		get { return isoriginal; } 
    		set
    		{
    			isoriginal = value;
    			OnPropertyChanged("IsOriginal");
    		} 
    	}
    
    	private Nullable<decimal> copies;
    
        public Nullable<decimal> Copies 
    	{ 
    		get { return copies; } 
    		set
    		{
    			copies = value;
    			OnPropertyChanged("Copies");
    		} 
    	}
    
    
        public virtual ICollection<Artist> Artists { get; set; }
        public virtual ICollection<Artist> Composers { get; set; }
    }
}
