//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Payments = new HashSet<Payment>();
            this.StudentAttendences = new HashSet<StudentAttendence>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.Guid> ChoirId { get; set; }
    
        public virtual Choir Choir { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<StudentAttendence> StudentAttendences { get; set; }
    }
}
