//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessManager.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    
    public partial class Student : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	protected virtual void OnPropertyChanged(string propertyName)
    	{
            if (PropertyChanged!= null) 
    		{
    			PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
    		}
    	}
    
        public Student()
        {
            this.Payments = new HashSet<Payment>();
            this.StudentAttendences = new HashSet<StudentAttendence>();
        }
    
    	private System.Guid id;
    
        public System.Guid Id 
    	{ 
    		get { return id; } 
    		set
    		{
    			id = value;
    			//OnPropertyChanged("Id");
    		} 
    	}
    
    	private string firstname;
    
        public string FirstName 
    	{ 
    		get { return firstname; } 
    		set
    		{
    			firstname = value;
    			//OnPropertyChanged("FirstName");
    		} 
    	}
    
    	private Nullable<System.Guid> choirid;
    
        public Nullable<System.Guid> ChoirId 
    	{ 
    		get { return choirid; } 
    		set
    		{
    			choirid = value;
    			//OnPropertyChanged("ChoirId");
    		} 
    	}
    
    
        public virtual Choir Choir { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<StudentAttendence> StudentAttendences { get; set; }
    }
}
